name: Build AmperageKite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    # Usunęliśmy matrix, serwer buduje teraz tylko jedną, właściwą wersję x64
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore AmperageKit.sln
      
    - name: Build Solution for x64
      run: |
        msbuild AmperageKit.sln /p:Configuration=Release /p:Platform=x64 /t:Rebuild

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AmperageKit-x64
        path: |
          **/bin/x64/Release/*.exe
          **/bin/x64/Release/*.dll
        if-no-files-found: error
